<<<<<<< HEAD
---
# https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
version: 1
disable_existing_loggers: "False"
formatters:
    MR2:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s] [Module: %(module)s] [Function: %(funcName)s(), Line:%(lineno)s] [PID:%(process)d,
        TID:%(thread)d] -> %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: MR2
        stream: ext://sys.stdout

    error_console:
        class: logging.StreamHandler
        level: ERROR
        formatter: MR2
        stream: ext://sys.stderr

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: MR2
        filename: logs/DRY.log
        maxBytes: 10485760  # 10MB
        backupCount: 200
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: MR2
        filename: logs/DRY_errors.log
        maxBytes: 10485760  # 10MB
        backupCount: 2000
        encoding: utf8


loggers:
    DRY:
        level: DEBUG
        handlers:
#            - console
            - error_console
            - debug_file_handler
            - error_file_handler
        propagate: False

    simpleExample:
        level: DEBUG
        handlers:
         - console
        propagate: False

root:
    level: DEBUG
    handlers:
#     - console
     - error_console
     - debug_file_handler
     - error_file_handler
#    handlers: [console, debug_file_handler, error_file_handler,]
=======
---
# https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
version: 1
disable_existing_loggers: "False"
formatters:
    MR2:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s] [Module: %(module)s] [Function: %(funcName)s(), Line:%(lineno)s] [PID:%(process)d,
        TID:%(thread)d] -> %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: MR2
        stream: ext://sys.stdout

    error_console:
        class: logging.StreamHandler
        level: ERROR
        formatter: MR2
        stream: ext://sys.stderr

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: MR2
        filename: logs/DRY.log
        maxBytes: 10485760  # 10MB
        backupCount: 200
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: MR2
        filename: logs/DRY_errors.log
        maxBytes: 10485760  # 10MB
        backupCount: 2000
        encoding: utf8


loggers:
    DRY:
        level: DEBUG
        handlers:
#            - console
            - error_console
            - debug_file_handler
            - error_file_handler
        propagate: False

    simpleExample:
        level: DEBUG
        handlers:
         - console
        propagate: False

root:
    level: DEBUG
    handlers:
#     - console
     - error_console
     - debug_file_handler
     - error_file_handler
#    handlers: [console, debug_file_handler, error_file_handler,]
>>>>>>> b1a358d956a698ed5377fec606bb14b84c58a0aa
